version: '3.8'

services:
  web:
    container_name: backend
    build: .
    volumes:
      - .:/backend
    command: sh ./entrypoint.sh
    ports:
      - '8080:8080'
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:13-alpine
    env_file: ./.env.dev
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'


volumes:
  pg_data:
    driver: local




